### ISSUE TITLE
Service failing to start

### ISSUE THREAD

**Issue by gazuzu** [diyhue/diyHue#14]
Hey guys,
First of all, thanks for all your hard work on this project, I really love it.

I am having a few issues however, with the service failing to start.
This has happened a a few times now, where after a restart the hue-emulator service just fails to start on my Raspberry Pi.

The only way I have been able to resolve this was by renaming /opt/hue-emulator and re-running the install.
This obviously wipes my configuration, but I am able to start the service again. After I stop the service, I copy the config.json file to the newly generated /opt/hue-emulator folder, to no avail, the service continues to refuse to start.

I don't have a massive number of devices so I have reconfigured everything a couple of times, until today where this happened again.

Obviously this isn't sustainable so I would very much appreciate your help trying to resolve and understand what exactly is causing this.
After this happened the last time I created a cron job to backup the whole /opt/hue-emulator folder, I have restored this but unfortunately this did not help. 

Please see below the journalctl output of when I try to start the service, and please do let me know if you need anything else in order to understand what's going on and how can I get the service to start again without wiping config.

pi@raspberrypi:/opt $ sudo journalctl -u hue-emulator.service
-- Logs begin at Fri 2018-12-14 20:41:29 GMT, end at Fri 2018-12-14 20:55:08 GMT. --
Dec 14 20:41:39 raspberrypi systemd[1]: Started Hue Emulator Service.
Dec 14 20:41:40 raspberrypi HueEmulator3.py[503]: Traceback (most recent call last):
Dec 14 20:41:40 raspberrypi HueEmulator3.py[503]:   File "/opt/hue-emulator/HueEmulator3.py", line 1723, in <module>
Dec 14 20:41:40 raspberrypi HueEmulator3.py[503]:     updateConfig()
Dec 14 20:41:40 raspberrypi HueEmulator3.py[503]:   File "/opt/hue-emulator/HueEmulator3.py", line 118, in updateConfig
Dec 14 20:41:40 raspberrypi HueEmulator3.py[503]:     if bridge_config["groups"][group]["type"] == "Entertainment":
Dec 14 20:41:40 raspberrypi HueEmulator3.py[503]: KeyError: 'type'
Dec 14 20:41:40 raspberrypi systemd[1]: hue-emulator.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 20:41:41 raspberrypi curl[522]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dec 14 20:41:41 raspberrypi curl[522]:                                  Dload  Upload   Total   Spent    Left  Speed
Dec 14 20:41:41 raspberrypi curl[522]: [147B blob data]
Dec 14 20:41:41 raspberrypi systemd[1]: hue-emulator.service: Control process exited, code=exited status=7
Dec 14 20:41:41 raspberrypi systemd[1]: hue-emulator.service: Unit entered failed state.
Dec 14 20:41:41 raspberrypi systemd[1]: hue-emulator.service: Failed with result 'exit-code'.
Dec 14 20:42:32 raspberrypi systemd[1]: hue-emulator.service: Service hold-off time over, scheduling restart.
Dec 14 20:42:33 raspberrypi systemd[1]: Stopped Hue Emulator Service.
Dec 14 20:42:33 raspberrypi systemd[1]: Started Hue Emulator Service.
Dec 14 20:42:34 raspberrypi HueEmulator3.py[573]: Traceback (most recent call last):
Dec 14 20:42:34 raspberrypi HueEmulator3.py[573]:   File "/opt/hue-emulator/HueEmulator3.py", line 1723, in <module>
Dec 14 20:42:34 raspberrypi HueEmulator3.py[573]:     updateConfig()
Dec 14 20:42:34 raspberrypi HueEmulator3.py[573]:   File "/opt/hue-emulator/HueEmulator3.py", line 118, in updateConfig
Dec 14 20:42:34 raspberrypi HueEmulator3.py[573]:     if bridge_config["groups"][group]["type"] == "Entertainment":

Your help is greatly appreciated.

**Comment by mariusmotea** [comment]
Looks like you have a group without type attribute. With what application you configure the rooms and what type of devices are you using?

**Comment by gazuzu** [comment]
I have used the Official Hue App (the 2nd one).

I have only configured 3 official Hue lights so far, in 3 Groups:
Kitchen Group > Kitchen Light
TV Group > TV Light
LivingRoom Group > LivingRoom Light

I have noticed however on the DIYHue webpage that the emulator creates another group called "Wake Up Group" (I believe), if I configure the lights with the Wake Up Feature of the Hue App. Not sure how relevant this is.
Please find attached the config.json (changed to .txt to allow upload) if this is of any help.

Thanks Marius
[config.txt](https://github.com/diyhue/diyHue/files/2681839/config.txt)

**Comment by gazuzu** [comment]
Hi Marius, your comment prompted me to look at the config and I found that this Wake Up Group indeed was missing "Type": "Group".

I removed this group and the service is able to start again, and I see the remaining lights in the control panel :)

As this was happening due to the Wake Up routine built in the Hue App itself, could we have perhaps found a bug?
Many thanks

**Comment by mariusmotea** [comment]
Yes, you found a bug. I will update the script tomorrow morning (EU time)

**Comment by mariusmotea** [comment]
Fixed.

**Comment by GreenGhost994** [comment]
I think there is still a problem.

On 2019-02-13 my hue-emulator stopped working.
I checked github and there was update of HueEmulator3.py. I tried to update HueEmulator. It didn't work. Then I tried to reinstall it. It worked until first raspberry reboot. My last hope was to reinstall raspbian. Fresh install on a RaspberryPi 3b+ and it didn't help.

I found this issue topic. If I don't add routine or hue labs there is no problem after RP reboot.
I had morining routine 3 or 4 days.  I think I restarted Raspberry at least once.

```
pi@raspberrypi:~ $ sudo systemctl stop hue-emulatorpi@raspberrypi:~ $ cd /opt/hue-emulator
pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py --debug True
Debug Enabled
2019-02-17 20:14:06,005 - root - INFO - b827eb22f394
2019-02-17 20:14:06,006 - root - INFO - IP range for light discovery: 0-255
2019-02-17 20:14:06,009 - root - INFO - Config loaded
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1874, in <module>
    updateConfig()
  File "./HueEmulator3.py", line 148, in updateConfig
    if bridge_config["groups"][group]["type"] == "Entertainment":
KeyError: 'type'

```

**Comment by mariusmotea** [comment]
I will fix it in few minutes

**Comment by mariusmotea** [comment]
seams this was fixed but your code is legacy:
on line 148 there are different things now and the fix for this issues is the following:
```    for group in bridge_config["groups"].keys():
        if "type" in bridge_config["groups"][group] and bridge_config["groups"][group]["type"] == "Entertainment":
            bridge_config["groups"][group]["stream"].update({"active": False, "owner": None})```

**Comment by joselito11** [comment]
Every sunnday evening diyhue freeze. It also freeze raspberry so I can not provide logs. This happened 3x in row every sunnday evening.
I have only diyhue on rasbian buster on rpi3.
