### ISSUE TITLE
Autoupdate swversion

### ISSUE THREAD

**Issue by Qballjos** [diyhue/diyHue#433]
**Describe the bug**
With the latest Philips hue app (3.41.0) de update fails (also with restart of emulator) after failing the app gives limited functionality.

**To Reproduce**
1. Go to appstore or playstore and update the hue app to latest version
2. after update open the app and immediately you will be notified of the update
3. Install the update
4. restart the emulator
5. restart the Hue app. (clear cache or reinstall doesn't work either)

**Expected behavior**
After emulator restart the app functions normally as if update has been installed

**Additional context**
after updating the sw version in HueEmulator3.py to 1939070020 every thing functions normally again

**Comment by panovvv** [comment]
Just to add to the previous comment, here are the commands I executed for this quick workaround (this assumes **Host install**):
```
sudo sed -i -e 's/1938112040/1939070020/g' /opt/hue-emulator/HueEmulator3.py
sudo systemctl restart hue-emulator.service

```

**Comment by alexyao2015** [comment]
Seems like a fix was merged but should look into automatically pulling latest swversion from the hue website.
https://www.philips-hue.com/en-us/support/release-notes/bridge

**Comment by minburg** [comment]
What is the correct way to update swversion for docker installs? Changing swversion to 1939070020 in config.json, then '{bridge-ip}/save' and docker restart did not fix the update warning in the android app for me.

**Comment by alexyao2015** [comment]
Should be able to simply delete the container, pull the latest version, and recreate the container.

**Comment by minburg** [comment]
I tried to do a fresh start(to be able to link with bridge again) but still no success.
I deleted config.json file(made a backup first), deleted container, and image so that everything would get pulled again.
I can find the bridge in official Android hue app automatically and manually but when I try to press the link button (http://{ip-bridge}/hue/linkbutton?username=&password=&action=Activate) nothing happens. What can I do to get access of the bridge with official app again? Don't mind setting up the lights and rooms again.

**Comment by ryancasler** [comment]
There is a default username and password for the link button.  The easiest way to activate the button is go to the DIYHue GUI and hit the button the left side of the screen.  You should get asked for a username and Password.  The default UN and Password are "Hue", unless you changed them.

**Comment by minburg** [comment]
Thanks, I tried it with authentication before. It works like a charm with the Hue Essentials App but not with official Hue app.
My setup is a Raspberry 4B as a diyHue bridge, an official Bridge for some official Hue lights and several diyHue lights.

Some Logcat of the Android app:
2020-08-05 17:17:50.001 1404-5143/? D/ActivityManager: setRequestedOrientation() to 1 for ActivityRecord{cb41f05 u0 com.philips.lighting.hue2/hue.features.bridgediscovery.DiscoveryActivity t474} from pid=21603, uid=10204

2020-08-05 17:17:50.291 1404-1444/? I/ActivityManager: Displayed com.philips.lighting.hue2/hue.features.bridgediscovery.DiscoveryActivity: +308ms (total +747ms)

2020-08-05 17:17:50.365 1404-4489/? W/ActivityManager: Unable to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.philips.lighting.hue2 } U=0: not found

2020-08-05 17:17:50.378 847-4269/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.philips.lighting.hue2#0

2020-08-05 17:17:50.379 847-4269/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.philips.lighting.hue2#0

2020-08-05 17:17:57.885 702-21792/? I/netd: ;; res_nquery(discovery.meethue.com, 1, 28)

2020-08-05 17:17:57.885 702-21792/? I/netd: ;; res_nquery(discovery.meethue.com, 1, 1)


And the relevant logs of the docker container:
192.168.2.39 - - [05/Aug/2020 17:18:01] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:01] code 404, message not found
192.168.2.39 - - [05/Aug/2020 17:18:01] "GET /favicon.ico HTTP/1.1" 404 -
192.168.2.39 - - [05/Aug/2020 17:18:02] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:02] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:03] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:03] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:04] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:04] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:05] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:05] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
{"ok"}
192.168.2.39 - - [05/Aug/2020 17:18:06] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:06] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:07] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:07] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:08] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:08] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:09] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:09] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:10] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:10] "GET /api/web-ui-29701/lights HTTP/1.1" 200 -
192.168.2.39 - - [05/Aug/2020 17:18:11] "GET /api/web-ui-29701/groups HTTP/1.1" 200 -


Somebody an Idea?

**Comment by minburg** [comment]
Nevermind, I had an error in the docker run command concerning the MAC adress of the raspberry. Now it works. Thanks anyways!

**Comment by panovvv** [comment]
A simple script to parse the latest version from the page:
```
ARR=$(curl https://www.philips-hue.com/en-us/support/release-notes/bridge | grep "Firmware [0-9]* (Bridge V2)" | grep -o " [0-9]*")
echo "${ARR[*]}" | sort -nr | head -n1
````
Could we incorporate that into the `easy_install` script?

**Comment by juanesf** [comment]
very good...
note: the script throws a space before the version numbers

**Comment by alexyao2015** [comment]
Ideally it would be part of the python code but good start.

Also #416

**Comment by panovvv** [comment]
Same in python:
```
import re
from urllib.request import urlopen

def extract_version(line):
    if match := re.search(r'Firmware ([0-9]*) \(Bridge V2\)', line, re.I):
        return int(match.group(1))

url = 'https://www.philips-hue.com/en-us/support/release-notes/bridge'
response = urlopen(url)
webpage_lines = [x for x in response.read().decode('utf-8').splitlines() if x]
versions = list(filter(None.__ne__, map(extract_version, webpage_lines)))
print(max(versions))
```
I don't have enough time to read through the code base and incorporate that unfortunately... Giving this snippet away to whoever understands the code more.
