### ISSUE TITLE
Hue Sync/Entertainment Failure

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#522]
**Describe the bug**

Starting Hue Entertainment results in disconnecting from the bridge, but mostly the hue sync app just can't find the bridge.

**Steps to Reproduce**

1. Open Hue Essentials/ Hue Sync (MacOS)
2. Start an entertainment effect or start sync

**Expected behavior**

The bridge should start syncing instead of disconnect

**Logs**

```
diyHue    | 2020-12-08 08:43:22,243 - webServer.server - INFO - in PUT method
diyHue    | 2020-12-08 08:43:22,245 - webServer.server - INFO - /api/hueess6a35bb11ebbc2bb827ebb5da33/groups/9
diyHue    | 2020-12-08 08:43:22,247 - webServer.server - INFO - b'{"stream":{"active":true}}'
diyHue    | 2020-12-08 08:43:22,248 - webServer.server - INFO - start hue entertainment
diyHue    | ----------------------------------------
diyHue    | Exception occurred during processing of request from ('192.168.2.26', 41360)
diyHue    | Traceback (most recent call last):
diyHue    |   File "/usr/local/lib/python3.9/socketserver.py", line 650, in process_request_thread
diyHue    |     self.finish_request(request, client_address)
diyHue    |   File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
diyHue    |     self.RequestHandlerClass(request, client_address, self)
diyHue    |   File "/usr/local/lib/python3.9/socketserver.py", line 720, in __init__
diyHue    |     self.handle()
diyHue    |   File "/usr/local/lib/python3.9/http/server.py", line 429, in handle
diyHue    |     self.handle_one_request()
diyHue    |   File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
diyHue    |     method()
diyHue    |   File "/diyhue/webServer/server.py", line 746, in do_PUT
diyHue    |     Popen([configManager.coreConfig.get_path("entertain-srv", project=True), "server_port=2100", "dtls=1",
diyHue    |   File "/usr/local/lib/python3.9/subprocess.py", line 947, in __init__
diyHue    |     self._execute_child(args, executable, preexec_fn, close_fds,
diyHue    |   File "/usr/local/lib/python3.9/subprocess.py", line 1819, in _execute_child
diyHue    |     raise child_exception_type(errno_num, err_msg, err_filename)
diyHue    | FileNotFoundError: [Errno 2] No such file or directory: '/diyhue/entertain-srv'
diyHue    | ----------------------------------------
diyHue    | 2020-12-08 08:43:22,656 - WebServer - DEBUG - 192.168.2.26 - "GET /api/hueess6a35bb11ebbc2bb827ebb5da33 HTTP/1.1" 200 -
diyHue    | 2020-12-08 08:43:22,753 - configManager.bridgeConfigHandler - DEBUG - Saving config!
```
**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): arm
 - Docker image version (Ex: latest, arm-05f043b, 128): experimental
 - OS (Ex: Windows 10, Ubuntu Buster): Raspberry Pi OS Buster
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  Raspberry Pi 3 B+

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

Docker config:
```
version: '3'
services:
  diyHue:
    image: diyhue/core:experimental
    # This makes for more convienient naming, but only allows one instance of the image
    container_name: diyHue
    restart: unless-stopped

    environment:
      # Uncomment to enable debug mode 
      DEBUG: "true"
      # IP and MAC are only needed for running diyHue in the bridge network
      #IP: 192.168.1.109
      #MAC: B8:27:EB:B5:DA:33
    volumes:
      - /mnt/hue-emulator:/config
    #ports:
      #- '95:95'
      #- '444:444'
      #- '1901:1901/udp'
      #- '2101:2101/udp'
      #- '1983:1983/udp'
    # Alternatively, you can activate host mode by uncommenting the line below and removing all ports and the env vars above
    network_mode: "host"
```

**Comment by alexyao2015** [comment]
Docker has some bug where it pulls down the wrong image for your architecture. Try manually selecting the architecture by using armv6-experimental for the image tag to force it to pull a different architecture.

**Comment by alexyao2015** [comment]
You can check available image tags on docker hub. If that image doesn't work for your architecture, try the other available architecture

**Comment by AlexKusnezov** [comment]
@alexyao2015 thanks, I pulled armv7. Entertainment is working now in Hue Essentials, unfortunately the Hue Sync app still doesn't find the bridge. Sometimes it find, but doesn't registers the link button. Any idea why? There's also nothing in deug. I'm on wired connection

**Comment by alexyao2015** [comment]
What is the exact name of the image you're using?

**Comment by AlexKusnezov** [comment]
https://hub.docker.com/layers/diyhue/core/armv7-experimental/images/sha256-fa1a94e1aa8b0f1762982c0459ffc9b06df814b18bc62da58527a0cbc6756eb5?context=explore

**Comment by alexyao2015** [comment]
Does the normal hue app work?

**Comment by alexyao2015** [comment]
Likely an issue with the Mac address not being set correctly

**Comment by AlexKusnezov** [comment]
@alexyao2015 hue app works very well. I actually use it as my primary app to control lights. I'm using network host mode, no issue with my mac addresd

**Comment by alexyao2015** [comment]
Then, I'm not sure why. Try manually entering the ip. I'll consider this issue solved as you now have the bug fixes.

**Comment by AlexKusnezov** [comment]
@alexyao2015 that's the thing, you can't enter in Hue Sync Ip manually. Anyway, I may revert back to master and test things there.

**Comment by alexyao2015** [comment]
Hmm. Would be curious if it does work there, because if it does, that would be a regression. Please open a new bug report if that's the case. 

Although would be very hard to debug without any sort of indication in the logs...

**Comment by AlexKusnezov** [comment]
@alexyao2015 with diyhue/core:latest I'm still not able to connect to the Hue Sync app. What I know for sure is, that I prefectly worked last week on wedndesday (2nd dec) with diyhue master branch. Can someone try it out with the current docker images (master+experimental). Maybe it's not only my setup

**Comment by alexyao2015** [comment]
Few questions. Does the entertainment setup work in the default hue app? What sw version does the hue app report?

**Comment by alexyao2015** [comment]
This might be related to #520 but I thought I fixed it?

**Comment by mariusmotea** [comment]
Probably you replaced the certificated and now you need to reinstall Hue Sync because detect a certificate change and believe there is [an attack](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)

**Comment by AlexKusnezov** [comment]
@alexyao2015 
>Does the entertainment setup work in the default hue app?

Yes, it does.
>What sw version does the hue app report?

1941132070

@mariusmotea 
>Probably you replaced the certificated and now you need to reinstall Hue Sync

I removed the app and clean my mac from previous prefs, but it is still not working.

**Comment by AlexKusnezov** [comment]
@mariusmotea I#ve also delted the certificate, pulled the docker image again and let the cert regenerate, did not helped for the Hue Sync. I also uninstalled Hue app on my phone and was able to connect to the bridge easily. I also tried another mac app "iLightShow" on the same machine and was also able to connect. 
Problem seems to be with the Hue Sync App itself

**Comment by mariusmotea** [comment]
Did you reinstall the Hue Sync app?

**Comment by AlexKusnezov** [comment]
@mariusmotea yes, I did that on all cases mentioned above

**Comment by mariusmotea** [comment]
If Hue app is working then the only issue with Hue Sync I believe must be the old certificate cached. No other pc, vm in your home network to test a fresh install of Hue Sync?

**Comment by AlexKusnezov** [comment]
@mariusmotea just tried it on my other machine which is a macmini, same thing, can't get past this:
![image](https://user-images.githubusercontent.com/33514406/101635851-cc90a100-3a2a-11eb-8f93-b1e13193da12.png)

**Comment by mariusmotea** [comment]
Can you try to press the link button before bridge search?

**Comment by AlexKusnezov** [comment]
@mariusmotea tried that too, but no luck. It also adds Hue Sync User, but nothing happens:
![image](https://user-images.githubusercontent.com/33514406/101636845-2e9dd600-3a2c-11eb-9573-39ae44be680b.png)

**Comment by mariusmotea** [comment]
Can be because something was changed in the configuration. Did you start with fresh config also, or preseve the existing ones? Also restart the hue-emulator service after you added the lights will help because it will patch the lights config.

**Comment by AlexKusnezov** [comment]
@mariusmotea 
>Did you start with fresh config also, or preseve the existing one?

Just tried it with fresh config, image: diyhue/core:armv7-experimental
 - no luck either, I don't know original Hue App is working, Ambilight+Hue on my Philips Oled TV is working

diyhue even adds **Hue Sync** as user, but the app is just stuck on **Searching for Hue bridges...** and don't even let's me enter the ip address manually

**Comment by mariusmotea** [comment]
And fresh install with diyhue/core image has the same result? Hue Essentials entertainment effects are working ?

**Comment by AlexKusnezov** [comment]
@mariusmotea 
>Hue Essentials entertainment effects are working ?
yes

Seems like everything is working, except for the Hue Sync App.

>And fresh install with diyhue/core image has the same result? 

I'll try that tomorrow, too

**Comment by mariusmotea** [comment]
Please post also some logs.

**Comment by alexyao2015** [comment]
This is a peculiar situation. We can't tell if this is a user/setup issue or if this is a bug related to diyhue....
Are you able to try a complete fresh start on a separate machine with diyhue and a new install of the hue sync app?

**Comment by AlexKusnezov** [comment]
@mariusmotea @alexyao2015 I rad diyhue:core on an entirely new setup:
diyhue in docker-compose debian 10
Huey Sync app on MacBook Pro
Fresh install,
 paired with Hue app, discovered lights, created rooms, created entertainment area, restarted container.

MacBook:
Installed Hue Sync app, granted permissions, launched, bridge discovered, connect

same thing - Hue Sync is not picking up the bridge

Debug log:
```
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:13] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:14] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:14] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:15] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:15] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:16] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:16] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:17] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:17] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:18] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:18] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:19] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:19] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:20] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:20] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:21] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:21] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:22] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:22] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:23] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:23] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:24] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:24] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:24,487 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:25] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:25] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:26] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:26] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:27] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:27] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:28] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:28] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:29] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:29] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:29,877 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:30] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:30] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:30,682 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:31] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:31] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:31,986 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:32] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:32] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:33,304 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:33] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:33] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:33,907 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:34] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:34] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:34,610 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:35] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:35] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:35,614 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:36] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:36] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:36,688 - root - INFO - sync with lights
diyHue    | 2020-12-11 11:29:36,819 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:37] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:37] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:38] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:38] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:39] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:39] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:40] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:40] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:40,914 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:41] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:41] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:42,168 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
diyHue    | {"ok"}
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:42] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:42] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:43] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:43] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:44] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:44] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:45] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:45] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:46] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:46] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:47] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:47] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:48] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:48] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:48,876 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:49] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:49] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:50] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:50] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:51] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:51] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:52] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:52] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:53] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:53] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:54] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:54] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:55] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:55] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:56,002 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:56] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:56] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:56,902 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:57] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:57] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:58] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:58] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:29:58,504 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 2020-12-11 11:29:59,208 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:59] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:29:59] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:00] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:00] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:01,072 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:01] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:01] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:02] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:02] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:03] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:03] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:04] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:04] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:04] "GET /api/nouser/config HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:04] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:04] "GET /api/a535248a3ba311eb987b000c29e3ebcf HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:05] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:05] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:06] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:06] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:07] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:07] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:08] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:08] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:08] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:09] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:09] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:10] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:10] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:11] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:11] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:12,205 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:12] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:12] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:12,487 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
diyHue    | {"ok"}
diyHue    | 2020-12-11 11:30:13,156 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:13] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:13] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:14] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:14] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:15] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:15] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:16] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:16] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:17] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:17] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:18] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:18] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:18] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:19] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:19] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:20] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:20] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:21] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:21] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:22] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:22] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:23] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:23] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:24] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:24] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:25,286 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:25] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:25] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:26] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:26] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:27] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:27] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:28] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:28] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:28] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:29] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:29] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:30] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:30] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:31] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:31] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:32] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:32] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:33] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:33] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:34] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:34] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:35] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:35] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:36] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:36] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:37] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:37] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:37,467 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:38] "GET /api/web-ui-93599/groups HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:38] "GET /api/web-ui-93599/lights HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:39] "GET /hue/linkbutton HTTP/1.1" 200 -
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:40] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:42,525 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
diyHue    | 2020-12-11 11:30:42,671 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
diyHue    | {"ok"}
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:48] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:30:49,670 - root - INFO - sync with lights
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:30:57] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:30:58] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:31:12,693 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
diyHue    | 2020-12-11 11:31:12,841 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
diyHue    | {"ok"}
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:31:13] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:31:15,491 - root - INFO - sync with lights
diyHue    | 192.168.2.26 - - [11/Dec/2020 11:31:28] "GET /api/a535248a3ba311eb987b000c29e3ebcf/config HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:31:29,684 - root - INFO - sync with lights
diyHue    | 2020-12-11 11:31:31,216 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:31,918 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:32,621 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:33,325 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:34,731 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:35,435 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:36,839 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:37,641 - root - DEBUG - Sending M-Search response to 192.168.2.19
diyHue    | 2020-12-11 11:31:43,115 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
diyHue    | 2020-12-11 11:31:43,679 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
diyHue    | {"ok"}
diyHue    | 192.168.2.105 - - [11/Dec/2020 11:31:55] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
diyHue    | 2020-12-11 11:31:56,399 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 2020-12-11 11:31:57,402 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 2020-12-11 11:31:58,404 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 2020-12-11 11:31:59,207 - root - DEBUG - Sending M-Search response to 192.168.2.2
diyHue    | 2020-12-11 11:32:13,698 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
diyHue    | 2020-12-11 11:32:13,876 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
diyHue    | {"ok"}


```

**Comment by mariusmotea** [comment]
Unfortunatelly you had the web ui page opened and it flood the log. I don't see any test pair try here. Anyway i take a look on my Windows machine and found the latest Hue Sync app did not pair because it made some wired requests

`GET /auth/v1 HTTP/1.1`. Try to find previews version of Hue Sync. I will try to understand what are these requests.

**Comment by mariusmotea** [comment]
I think i found the issue. When the entertainment room is made from Hue Essentials probably some keys are missing. From Hue app the pair process is working perfectly. I will insperc and made it to work also with Hue Essentials
