### ISSUE TITLE
Fail to start? KeyError: 'Type'

### ISSUE THREAD

**Issue by chrisdata** [diyhue/diyHue#64]
```
Traceback (most recent call last):
  File "./HueEmulator3.py", line 1847, in <module>
    updateConfig()
  File "./HueEmulator3.py", line 147, in updateConfig
    if bridge_config["groups"][group]["type"] == "Entertainment":
KeyError: 'type'
```

Just try to start manually in VM Ubuntu.

**Comment by mariusmotea** [comment]
Are you using an old version? I believe this was fixed as the error was already reported

**Comment by morphygee** [comment]
the problem persists if you are using the auto install option. (I was not able to pair the diybridge to app after manual installation)
so I still can not use wake up or other routines
