### ISSUE TITLE
Can't create routin

### ISSUE THREAD

**Issue by emmericp** [diyhue/diyHue#802]
**Describe the bug**
Can't create a routine

**Steps to Reproduce**
Fresh installation, :latest docker container, lights defined via zigbee2mqtt, everything works fine except creating a routine.
When finalizing the creation in the app it shows the error from the log below. Routine is not created, app stays in the creation dialog.

**Expected behavior**

A routine to be created

**Logs**

```
192.168.188.35 - - [01/Apr/2022 19:17:03] "POST /clip/v2/resource/behavior_instance HTTP/1.1" 200 -
192.168.188.35 - - [01/Apr/2022 19:17:03] "GET /clip/v2/resource/behavior_instance/77401241-f06b-412c-924c-a1b2e10128ca HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 315, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/wsgi.py", line 462, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.9/dist-packages/flask/helpers.py", line 131, in generator
    yield from gen
  File "/opt/hue-emulator/services/eventStreamer.py", line 27, in generate
    yield f"id: {int(time()) }:{index}\ndata: {json.dumps([messages], separators=(',', ':'))}\n\n"
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
192.168.188.35 - - [01/Apr/2022 19:17:03] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 315, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/wsgi.py", line 462, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.9/dist-packages/flask/helpers.py", line 131, in generator
    yield from gen
  File "/opt/hue-emulator/services/eventStreamer.py", line 27, in generate
    yield f"id: {int(time()) }:{index}\ndata: {json.dumps([messages], separators=(',', ':'))}\n\n"
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
```

**Docker Info (please complete the following information):**
 - Architecture arm64
 - Docker image version  latest
 - OS  latest raspian
 - Hardware rpi 3b+

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
found the issue that cause the error you pasted and commit a fix. Please let me know id the issue is fixed after you upgrade.

**Comment by emmericp** [comment]
Thank you, unfortunately it still doesn't work.

Creating a routine now mostly works except that the dialog in the iOS app doesn't close (and tapping the button multiple times creates more instances). But they are created correctly.

Unfortunately they fail to run with this error:

```
2022-04-02 19:20:00,900 - services.scheduler - INFO - execute timmer: Test 
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/functions/scripts.py", line 66, in triggerScript
    scene.activate({})
AttributeError: 'NoneType' object has no attribute 'activate'
```


Also, attempting to edit them fails with the same error as creating did before:

```
192.168.188.35 - - [02/Apr/2022 19:32:13] "PUT /clip/v2/resource/behavior_instance/09a9a857-2db3-4f69-8965-6b27e0a5f88e HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 315, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/wsgi.py", line 462, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/wrappers/response.py", line 50, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.9/dist-packages/flask/helpers.py", line 131, in generator
    yield from gen
  File "/opt/hue-emulator/services/eventStreamer.py", line 27, in generate
    yield f"id: {int(time()) }:{index}\ndata: {json.dumps([messages], separators=(',', ':'))}\n\n"
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
192.168.188.35 - - [02/Apr/2022 19:32:13] "GET /eventstream/clip/v2 HTTP/1.1" 200 -
```

**Comment by mariusmotea** [comment]
Avoid the default scenes from the bridge. Try to activate a scene created by you (from catalog or manually from current light state)

**Comment by emmericp** [comment]
That worked for triggering it, thanks. The bug around editing remains.

**Comment by mariusmotea** [comment]
I fix also that one, but display issue is still there. You need to reopen the app to see the changes where applied. So far i don't know what cause this issue.

**Comment by emmericp** [comment]
Thanks, I can confirm that it’s working now (except not closing the dialog, but that’s not too important for me)
